<footer class="footer">
    <div class="footer-flexbox">
        <div class="footer-flexbox-item">
            <div class="footer-flexbox-content">
                <p id="logo_spacing"></p>
                <a href="index.php" class="footer_logo"><img src="images/logowhite.png" alt="Logo" class="logo" height="40" width="100"><br></a>
                <a href="https://www.facebook.com/" class="fa fa-facebook"></a>
                <a href="https://twitter.com/i/flow/login" class="fa fa-twitter"></a>
                <a href="https://www.instagram.com/accounts/login/" class="fa fa-instagram"></a>
                <a href="https://www.linkedin.com/login" class="fa fa-linkedin"></a>
            </div>
        </div>
        <div class="footer-flexbox-item">
            <div class="footer-flexbox-content">
                <p>Cameras</p>
                <ul>
                    <li><a href="product.php#dslrcamera">DSLR Cameras</a></li>
                    <li><a href="product.php#mirrorlesscamera">Mirrorless Cameras</a></li>
                    <li><a href="product.php#videocamera">Video Cameras</a></li>
                    <li><a href="product.php#compactcamera">Compact Cameras</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-flexbox-item">
            <div class="footer-flexbox-content">
                <p>About Us</p>
                <ul>
                    <li><a href="about.php">About us</a></li>
                    <li><a href="enhancements.php">Enhancement</a></li>
                    <li><a href="enhancements2.php">PHP Enhancement</a></li>
                    <li><a href="product.php">Product</a></li>
                    <li><a href="index.php">Home Page</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div id="endfooter">
        <p id="copyright">Copy right &copy; 2022 PicFlix Inc. All rights reserved.</p>
    </div>
</footer>